[package]
name = "dsync-hasezoey"
description = "Generate rust structs & query functions from diesel schema files."
version = "0.0.13"
readme = "README.md"
repository = "https://github.com/hasezoey/dsync"
license = "MIT OR Apache-2.0"
keywords = ["diesel", "crud", "database", "codegen", "generation"]
categories = ["command-line-utilities", "development-tools", "development-tools::ffi", "web-programming"]
authors = ["Haris <4259838+Wulf@users.noreply.github.com>", "hasezoey <hasezoey@gmail.com>"]
edition = "2021"

[features]
default = ["tsync"]
tsync = []
async = []

[dependencies]
structopt = "0.3"
libdsync-hasezoey = { path = "../lib" }

[[bin]]
name = "dsync"
test = false
path = "src/main.rs"
